disabled_rules:
  - control_statement
  - function_body_length
  - line_length
  - type_body_length
  - variable_name

included:
  - Example
  - Source
  - Tests

variable_name_min_length:
  - 2 # warning
  - 2 # error
