disabled_rules:
  - conditional_binding_cascade
  - control_statement
  - file_length
  - function_body_length
  - function_parameter_count
  - implicit_getter
  - line_length
  - type_body_length
  - variable_name
  - unused_optional_binding

included:
  - SampleApplication
  - Source
  - Tests

variable_name_min_length:
  - 2 # warning
  - 2 # error
