language: objective-c

osx_image: xcode7.3

env:
  - SCHEME=UpholdSdk
  - SCHEME=UpholdSdkSandbox

before_script:
  - brew update
  - brew install swiftlint
  # Workaround to fix xctool issue #666(https://github.com/facebook/xctool/issues/666)
  - brew reinstall --HEAD xctool
  - carthage update --platform iOS
  # Workaround introduced to fix the xctool issue #454 (https://github.com/facebook/xctool/issues/454).
  - open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 75FC400A-B2AA-4DD6-B159-8687FAA5018A

script:
  - swiftlint lint --strict
  - xctool -project UpholdSdk.xcodeproj -scheme $SCHEME test sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
